#TODO: Validar tipos
Hour<-R6Class("Hour",portable=F,
              private=list(
                meanSpeed="numeric",
                maxiumSpeed="numeric",
                miniumSpeed="numeric",
                meanTemperature="numeric",
                maxiumTemperature="numeric",
                miniumTemperature="numeric",
                direction="numeric",
                date="Date"),
              public=list(
                initialize=function(pMeanSpeed,pMaxiumSpeed,pMiniumSpeed,pMeanTemperature,pMaxiumTemperature,pMiniumTemperature,pDirection,pDate)
                {
                  private$meanSpeed=pMeanSpeed;
                  private$maxiumSpeed=pMaxiumSpeed;
                  private$miniumSpeed=pMiniumSpeed;
                  private$meanTemperature=pMeanTemperature;
                  private$maxiumTemperature=pMaxiumTemperature;
                  private$miniumTemperature=pMiniumTemperature;
                  private$direction=pDirection;
                  private$date=pDate;
                },
                getDate=function()
                {
                  return(private$date);
                },
                getMeanSpeed=function()
                {
                  return(private$meanSpeed);
                },
                getMaxiumSpeed=function()
                {
                  return(private$maxiumSpeed);
                },
                getMiniumSpeed=function()
                {
                  return(private$miniumSpeed);
                },
                getMeanTemperature=function()
                {
                  return(private$meanTemperature);
                },
                getMaxiumTemperature=function(){
                  return(private$maxiumTemperature);
                },
                getMiniumTemperature=function(){
                  return(private$miniumTemperature)
                },
                getDirection=function()
                {
                  return(private$direction);
                }
                  ))